---
- name: exemplo de operador condicional
  hosts: all
  tasks:
   - name: testando o arquivo do profile
     command: "test -f /etc/profile.d/dexter"
     register: result
     #Se o comando acima der erro, ele ignora e continua com o processo
     ignore_errors: yes

     #O Debug vai ser realizado onde a variavel result for declarada, como no modo acima
   #- name: valor de variaveis
    # debug:
     # var: result

   - name: configurando a variavel com condicao
     shell: 'echo "sou devops" > /etc/profile.d/dexter'
     when: result.rc == 0 
