---
#Chamada: ansible-playbook -e "maquina=docker, usuario=devops" utils-variavel.yml
- name: utilizando variavel na playbook
  hosts: "{{maquina}}"
  vars:
   - maquina: default
   - usuario: usuario
  tasks:
   - name: verificando usuario 
     user:
      name: "{{usuario}}"
      state: present 
