---
- name: Criando usuarios padroes
  user:
   name: "{{item.nome}}"
   shell: "{{item.bash}}"
   password: "{{item.senha}}"
   home: "{{item.home}}"
  with_items:
   - { nome: junior, bash: /bin/bash, senha: '$1$yuch7EgE$cgnvQ5izB4d6LUmMlBJe00', home:/home/junior } 
   - { nome: developer, bash: /bin/bash, senha: '$1$yuch7EgE$cgnvQ5izB4d6LUmMlBJe00', home:/home/developer } 
   - { nome: devops, bash: /bin/bash, senha: '$1$yuch7EgE$cgnvQ5izB4d6LUmMlBJe00', home:/home/devops } 
